examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/jsbindings/rcvrcore/SceneManager.js

Isolate setting initial focus only to top level scene container and not child scene containers when scenes-by-url are created.

Fix focus from top level scene to child level scene

---

examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/jsbindings/rcvrcore/SceneModuleLoader.js
examples/pxScene2d/src/jsbindings/rcvrcore/XModule.js
examples/pxScene2d/src/jsbindings/rcvrcore/pxRoot.js
examples/pxScene2d/src/jsbindings/rcvrcore/utils/FileArchive.js

1) Allow autosensing of jar versus JavaScript files.
2) Added new px.import mechanism to pass resolved imports as a single object that contains all resolved exports per name.
3) Force users of px.import to hardcode use of '.js' instead of allowing it to be appended like Node require() does.  This was requested during our onsite meetings.
4) Renamed PxRoot to pxRoot per John's request.
5) Miscellaneous code cleanup

Modifications for requests brought up at during our onsite meetings

---

examples/pxScene2d/src/jsbindings/start.js

PxRoot is now pxRoot.
Also, temporarily includes an optional command line argument to still allow Node style imports that don't specify '.js'.   This is to temporarily allow some existing tests to work.   This value defaults to false.

Modified PxRoot to now be pxRoot per JR's request

---

examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/jsbindings/rcvrcore/SceneModuleLoader.js
examples/pxScene2d/src/jsbindings/rcvrcore/XModule.js
examples/pxScene2d/src/jsbindings/rcvrcore/utils/FileArchive.js

Added support for relative paths and per module base path.
Cleaned out old public class support.
Improved error percolation on promise failures.
Tested against:
receiver files and jar file on our Amazon server.
receiver files and jar file on localhost
local filesystem gallery in ./examples/
local filesystem browser.js

Per onsite meeting agreements, these changes implement module relative path for px.import

---

examples/pxScene2d/src/jsbindings/browser.js
examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/jsbindings/rcvrcore/SceneModuleLoader.js
examples/pxScene2d/src/jsbindings/rcvrcore/XModule.js
examples/pxScene2d/src/jsbindings/rcvrcore/scene.1.js
examples/pxScene2d/src/jsbindings/rcvrcore/utils/FileUtils.js

Added new scene.1.js wrapper for nativeScene.
Added new support for style pattern matching, through scene.1.js
New support for px:scene1.js import.  Note the the nativeScene is no longer part of the app sandbox context.  Scene is now picked up using px.import( ...px:scene.1.js... ).
Reorganize variable variables and methods into px namespace from app and module.

Added new support for px:scene.1.js import.  Also, reorganization of namespaces.

---

examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/jsbindings/rcvrcore/pxRoot.js
examples/pxScene2d/src/jsbindings/rcvrcore/rpcContext.js
examples/pxScene2d/src/jsbindings/rcvrcore/rpcController.js
examples/pxScene2d/src/jsbindings/rcvrcore/scene.1.js

px:scene.1-based support for RPC per getRPCContext spec.
rpc = scene.getRPCContext();
rpc.registerApp(appNamespace);
rpc.registerFunction(functionName, filters);
rpc.execute(appId, functionName, args, callback);

Added new px:scene.1-based support for RPC per getRPCContext spec

---

src/pxPixels.h

When iterating with p++, in pxBuffer::fill, the assumption is to have 4-byte increment, which is not always true for "long" values

Fixing a crash/memory corruption

---

examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h

pxWayland is now a pxIView and when pxScene2d creates an wayland instance it places it within a pxWaylandContainer.  All events and properties formerly accessible from pxWayland are now accessible from pxWaylandContainer.  The refactoring includes some variable name changes to better match the overall style of pxScene code.

Refactor pxWayland as a pxIView

---

examples/pxScene2d/src/rpc/rtRemoteResolver.cpp
examples/pxScene2d/src/rpc/rtRemoteServer.cpp
examples/pxScene2d/src/rpc/rtRemoteStream.cpp
examples/pxScene2d/src/rpc/rtSocketUtils.cpp
examples/pxScene2d/src/rpc/rtSocketUtils.h

also, refactoring: moving the tcp option setting to utils module

Avoid setting TCP_NODELAY option to sockets with non-TCP types

---

examples/pxScene2d/src/rpc/rtValueWriter.cpp

After the commit it would be possible to call methods with int64 and uint64 params.

Added int64_t and uint64_t rtValue support

---

examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/rpc/rtRemoteClient.cpp
examples/pxScene2d/src/rpc/rtValueReader.cpp

Kindly review. Changes are made to call rtremote properties/methods from javascript.
Example usage from javascript:
var wayland = <get pxwayland object>;
var remoteObj = wayland.api;
remoteObject.propertyX = "value";
remoteObj.funcX();
var propertyY = remoteObject.propertyY;

Updates for making calling rtremote properties/methods from javascript

---

examples/pxScene2d/src/jsbindings/rtObjectWrapper.cpp

Sometimes,when timeout happened , object is assumed as array of length 0 and sent to javascript

Handling timeout scenarios, when length property is queried.

---

examples/pxScene2d/src/Makefile
examples/pxScene2d/src/rpc/Makefile

In addition to that, added cleanobjdir as dependency for pxscene.so, pxwayland.so & pxwayland_s.a. 
This is to remove previously built object files before building either pxscene/pxwayland as they both have different compilation switches ("-DENABLE_RT_NODE")

Generate static libs with "_s" suffix

---

examples/pxScene2d/src/Makefile
examples/pxScene2d/src/rpc/Makefile

* Build librtCore.so / librtCore_s.a based on switch "PXCORE_STATIC_LIBS"
* Remove building librtRemote* for DFB platform

Updation to build dynamic/static libs for rtCore & rtRemote through switch

---

examples/pxScene2d/src/Makefile
examples/pxScene2d/src/rpc/rtRemoteMulticastResolver.cpp

Two commits;
First one fixes typo which breaks the build in runtime
Second unwires pxWayland from libnode and pxscene

Build fix and unwiring pxwayland from libnode/pxscene

---

examples/pxScene2d/src/pxWayland.cpp

If client (browser) has been terminated.
pxWayland will try to look up it anyway before it timed out.
In real case in Receiver it could be like:
1. startup screen is used to be shown on startup.
browser should be used to show it.
2. When root app is connected, need to hide all open pages.
This will lead to destroy graphics web view with browser adapter,
which removes plugin instance.
3. Client will be stopped abnormal.

Fixed latency while starting

---

remote/tests/perf_driver.cpp

I am not sure about the changes in "timeval_subtract" in "perf_driver.cpp" .

 printing test timing information

---

examples/pxScene2d/src/browser.js
examples/pxScene2d/src/shell.js

FPS box - when invisible was eating click events to edit box in **browser.js** .  Making FPS inactive fixes.

Making FPS box inactive. Transparent to click events etc.

---

examples/pxScene2d/src/pxWayland.cpp

When rendering to default FBO the post rendering hole punching will clear everything, for example when there is a westerossink playing fullscreen.

Don't do hole punching when drawing without FBO

---

examples/pxScene2d/src/pxFont.cpp
examples/pxScene2d/src/pxFont.h
examples/pxScene2d/src/pxText.cpp
examples/pxScene2d/src/pxTextBox.cpp

See textscale.js example.
- Separated glyph texture caching from glyph metric caching.
- Glyph textures are no longer one for one with a glyph's pixelSize.  A given pixelSize glyph may use the texture from a larger pixelSize glyph.  This reduces overall memory and provides more pixel data for sampling.
- Glyph rendering is done using the exact metrics for the specific pixelSize as reported by free type.  The selected glyph texture (which may be for a larger pixelSize) is scaled (down) to fit inside the glyph bounding box for the specificed pixelSize.
- Glyph texture selection now takes into account the necessary LOD (Level of Detail) needed based on sx and sy scale factors.  Greatly improving visual quality when scaling text.

Improved visual quality for scaled text and bugs

---

examples/pxScene2d/external/googleJScc/COPYING
examples/pxScene2d/external/googleJScc/README.md
examples/pxScene2d/src/jsMin.sh

Adding GOOGLE Closure Compiler to 'external' folder.
I suggest using it on all the **pxscene** JS files and use common naming such as **shell.min.js** ... changing in JS and C++ code as needed.
We would keep  **shell.js** and *shell.min.js** packaging the latter for deployment.
Defaulting to _minified_ (optimized) code would become the norm... when the source JS retained for development and debug.

Adding GOOGLE Closure Compiler to 'external' folder.

---

examples/pxScene2d/src/rcvrcore/AppSceneContext.js

This address leaks due to below cases:
1, any js file that exports any objects to the container with,
module.exports.obj1
module.exports.obj2
2,any js file, which imports user-defined js file

fix for leaks fue to module exports and import of user-defined js file

---

pxCore.xcodeproj/project.pbxproj

Removed **Rasterizer** files from **pxCore Static Library** build.

Removing Rasterizer files from pxCore build

---

examples/pxScene2d/src/Makefile
examples/pxScene2d/src/pxAnimate.cpp
examples/pxScene2d/src/pxAnimate.h
examples/pxScene2d/src/pxConstants.cpp
examples/pxScene2d/src/pxConstants.h
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h

With this, below way of animation is introduced:
var animateObj = obj.animate();
animateObj.done.then();
Animation can be cancelled as below:
animateObj.cancel - true;
Below are the properties that can be queried:
done -> promise to indicate completion of animation
type -> type of animation
interp -> interpolators of animation
status -> status of animation IDLE,INPROGRESS,ENDED,CANCELLED
provduration -> provisioned duration of animation by end user
provcount -> provisioned count of animation by end user
cancel -> status of animation, is it cancelled or not
props -> properties added for animation like x,y etc
details -> details of status of animation of every property.

introducing animation api returning animation object

---

src/x11/pxWindowNative.cpp

The fix was to include the file containing the symbol.
System experiencing failure was Fedora 25.

Make for X11 on Linux failed due on missing symbol

---

examples/pxScene2d/src/pxWayland.cpp
tests/pxScene2d/CMakeLists.txt
tests/pxScene2d/Makefile
tests/pxScene2d/test_pxWayland.cpp

When a pxWayland instance is destroyed, it stops and destroys its Westeros compositor instance and this will usually trigger the exit of any client process attached to the compositor.  It is possible that the client will not exit, however, so code is added to explicitly kill the client process if it does not exit on its own
Signed-off-by: Jeff Wannamaker <jeff_wannamaker@cable.comcast.com>

Kill wayland client if necessary

---

examples/pxScene2d/src/pxWaylandContainer.cpp
examples/pxScene2d/src/waylandregistry.conf

Wayland registry entries with a '%' suffix on the specified binary will now allow arguments.  The command supplied by JavaScript excluding any arguments will be used as the registry search key and the regstry binary will be invoked with the supplied arguments.
Added entries to waylandregistry.conf for westeros_test and gst-launch allowing arguments
Signed-off-by: Jeff Wannamaker <jeff_wannamaker@cable.comcast.com>

Update wayland registry to allow arguments

---

examples/pxScene2d/src/pxWayland.cpp

Signed-off-by: nrajang <nambirajan.g@lnttechservices.com>

Linux Key code for PX_KEY_PAGEDOWN is incorrectly mapped

---

src/pxUtil.cpp

Fix an issue detected by coverity.

Free memory within the scope it was allocated

---

tests/pxScene2d/test_api.cpp
tests/pxScene2d/test_imagecache.cpp
tests/pxScene2d/test_jsfiles.cpp
tests/pxScene2d/test_memoryleak.cpp
tests/pxScene2d/test_pxAnimate.cpp
tests/pxScene2d/test_pxImage.cpp
tests/pxScene2d/test_pxUtil.cpp
tests/pxScene2d/test_rtError.cpp
tests/pxScene2d/test_rtFile.cpp
tests/pxScene2d/test_rtString.cpp
tests/pxScene2d/test_rtZip.cpp

https://github.com/johnrobinsn/pxCore/issues/401

Fixing a build error in unit tests caused by keyword redefinition

---

examples/pxScene2d/src/pxImage.cpp
examples/pxScene2d/src/pxImageA.cpp
examples/pxScene2d/src/pxImageA.h
tests/pxScene2d/testRunner/tests.json

Reject promise if trying to assign an incompatible resource obj to 'resource' property.  Make url for pxImageA come from resource rather than separate property.

pxImage and pxImageA changes for issues discovered while adding tests

---

remote/rapidjson/rapidjson.h
src/rtNode.h

Rapidjson's RAPIDJSON_HAS_CXX11_RVALUE_REFS define statement was bad.
Rapidjson has fixed this in later versions.
When not compiled on a mac platform, the `#pragma gcc` statement caused
the clang build to fail.  This statement is now ignored under llvm's
toolchaein

Enable compiling with llvm toolchain

---

.travis.yml
ci/after_script.sh
ci/pxscene_generate_cache.json

There is a new server instance that must be used for posting of ci and release build results, reports and artifacts. This new IP address reflects the new server.

Change address for ci results server

---

remote/Makefile
remote/rtRemoteClient.cpp
remote/rtRemoteFunction.h
remote/rtRemoteObject.h
remote/rtRemoteServer.cpp
remote/rtRemoteStreamSelector.cpp
remote/rtRemoteStreamSelector.h
remote/rtRemoteValueReader.cpp
remote/rtRemoteValueReader.h
remote/rtRemoteValueWriter.cpp
remote/rtSampleClient.cpp
remote/rtSampleServer.cpp

When initializing and shutting down rtRemote without actually
making any inbound or outbound connections, the shutdown
will hang on processing queue being empty. That is now fixed.

Fixed deadlock on shutown.

---

ci/before_install.sh
ci/generate_cache_install.sh
examples/pxScene2d/README.md
examples/pxScene2d/external/build.sh
examples/pxScene2d/external/clean.sh

Please find the modifications related to Removal of external/freeglut related information and x11proto-input-dev.
And regarding the comment on earlier review "Also, of course, we want the changes to the readme to reverse the freeglut instructions from this commit: 1799b5d#diff-9669f884fa4e0ff4dcb39947bd039bc7" -> This information was already removed in the commit (bc8f818) Kindly confirm.

Removal of freeglut related information

---

remote/rtRemoteConfigGen.cpp

It fixes the following compilation error (using gcc 7.2):
$ make
[CC] rtRemoteConfigGen.cpp
rtRemoteConfigGen.cpp:121:8: error: ‘std::function’ has not been declared
std::function<void (FILE* , ConfigItem const& )> func)
^~~~~~~~
rtRemoteConfigGen.cpp:121:16: error: expected ‘,’ or ‘...’ before ‘<’ token
std::function<void (FILE* , ConfigItem const& )> func)
^
rtRemoteConfigGen.cpp: In function ‘void processConfigParamList(FILE*, const Value&, int)’:
rtRemoteConfigGen.cpp:141:5: error: ‘func’ was not declared in this scope
func(f, item);
^~~~
rtRemoteConfigGen.cpp:141:5: note: suggested alternative: ‘fputc’
func(f, item);
^~~~
fputc
rtRemoteConfigGen.cpp: In function ‘std::set<ConfigItem> buildConfigItems(const Value&)’:
rtRemoteConfigGen.cpp:166:4: error: cannot convert …

add missing header file

---

remote/CMakeLists.txt

All generated files are placed in CMAKE_CURRENT_BIN_DIR
to avoid polluting CMAKE_(CURRENT_)SOURCE_DIR directory.

add support for auto-generated files using cmake

---

src/gles/pxWindowNative.cpp

List of fixed issues:
pxWindowNative.cpp:444:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
for (int i = 0; i < keyEvents.size(); i++)
~~^~~~~~~~~~~~~~~~~~
pxWindowNative.cpp:462:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
for (int i = 0; i < mouseEvents.size(); i++)
~~^~~~~~~~~~~~~~~~~~~~
pxWindowNative.cpp: In static member function ‘static void pxWindowNative::keyEventListener(const pxKeyEvent&, void*)’:
pxWindowNative.cpp:530:19: error: unused variable ‘p’ [-Werror=unused-variable]
pxWindowNative* p = reinterpret_cast<pxWindowNative *>(argp);
^
pxWindowNative.cpp: In static member function ‘static void pxWindowNative::mouseEventListener(const pxMouseEvent&, void*)’: …

fix compilation errors in pxWindowNative.cpp

---

src/rtNode.h

In file included from pxscene/pxCore/src/rtNode.cpp:56:0:
pxCore/src/rtNode.h:39:32: error: ‘-Werror’ is not an option that controls warnings [-Werror=pragmas]
#pragma GCC diagnostic ignored "-Werror"
^~~~~~~~~

remove unsupported GCC pragma

---

examples/pxScene2d/src/browser.js

Fix so that ENTER key is only handled by browser.js if text box has focus.

Fix ENTER key handling

---

remote/Makefile

Add missing deletion of rtRemoteConfigBuilder.cpp auto-generated file.

fix make 'clean' target

---

src/rtNode.h
src/rtNodeMT.h
src/rtNodeST.h
src/rtNodeThread.h

1. It would make easier to use source files to compile with system Node.js.
2. Currently NODEINC already contains '${NODEDIR}/deps/v8/include' which
allow us to include "v8.h" directly instead of "include/v8.h".

fix include directory for v8

---

ci/before_install.sh
examples/pxScene2d/external/breakpad-chrome_55/patches/0001-replace-struct-ucontext-with-ucontext_t.patch
examples/pxScene2d/external/build.sh

Compilation log excerpt:
src/client/linux/dump_writer_common/ucontext_reader.cc: In static member function ‘static uintptr_t google_breakpad::UContextReader::GetStackPointer(const google_breakpad::ucontext*)’:
src/client/linux/dump_writer_common/ucontext_reader.cc:92:12: error: invalid use of incomplete type ‘const struct google_breakpad::ucontext’
return uc->uc_mcontext.gregs[REG_RSP];
^~
In file included from src/client/linux/dump_writer_common/ucontext_reader.cc:30:0:
./src/client/linux/dump_writer_common/ucontext_reader.h:44:49: note: forward declaration of ‘struct google_breakpad::ucontext’
static uintptr_t GetStackPointer(const struct ucontext* uc);
^~~~~~~~
src/client/linux/dump_writer_common/ucontext_reader.cc:92:14: error: invalid use of incomplete type ‘const struct …

fix breakpad compilation error

---

examples/pxScene2d/external/build.sh

It makes easier to build Node.js library when the link has been
updated and refers to a different version.

use link instead of file name for building Node.js

---

src/rtObjectMacros.h

This is an output pointer which could be NULL but hard for compiler to
detect that in a macro
Ideally, macros in c++ are not encouraged, they should be converted into
static inlines, however if we want to keep using macros compilers can
warn about address comparison
error: the compiler can assume that the address of 'r' will always evaluate to 'true' [-Werror=address]
Signed-off-by: Khem Raj <raj.khem@gmail.com>

src/rtObjectMacros.h: Type address to uintptr_t for comparision in macro

---

.editorconfig

Automatically works within github and multiple other editors (with and
without plugins) to enforce and guide code style.

Add an editorconfig for code style

---

remote/CMakeLists.txt

Usage:
1. Native build
a) from 'build-native' directory
b) cmake ../remote
c) make rtRemoteConfigGen VERBOSE=1
2. Target build (assumes CMAKE_CROSSCOMPILING is ON)
a) from 'build-target' directory
b) cmake -DRTREMOTE_GENERATOR_EXPORT=./build-native/rtRemoteConfigGen_export.cmake ..
c) make VERBOSE=1

add cross-compilation support for rtRemoteConfigGen tool

---

examples/pxScene2d/src/rcvrcore/AppSceneContext.js

loadScene and getPackageBaseFilePath did not handle full Windows file paths when launching from the MS Visual Studio Code IDE and in some command line situations.  These changes evaluate for the existence of the win32 platform and the use of a drive name, and if this condition occurs, then the full path is used.

Handle full Windows OS file paths in order to use Microsoft Visual Studio Code

---

examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
src/rtPermissions.cpp
src/rtPermissions.h
tests/pxScene2d/supportfiles/pxscenepermissions.sample.conf
tests/pxScene2d/test_rtPermissions1.cpp
tests/pxScene2d/test_rtPermissions2.cpp
tests/pxScene2d/test_rtPermissions3.cpp
tests/pxScene2d/test_rtPermissions4.cpp

redesigned rtPermissions to not expose custom URL schemes (added enum instead);
reworked tests to reuse rtPermissions objects and include wayland apps

permissions for wayland apps;

---

ci/before_install.sh
examples/pxScene2d/external/build.sh
examples/pxScene2d/external/buildWindows.bat
examples/pxScene2d/external/clean.sh
examples/pxScene2d/external/dukluv/patches/dukluv.git.patch
examples/pxScene2d/external/dukluv/patches/series

- allows build.sh & clean.sh to be run multiple times without errors,
- fix buildWindows.bat after #794 merge.

fixes for build.sh clean.sh and buildWindows.bat scripts

---

remote/rtRemoteMulticastResolver.cpp
remote/rtRemoteServer.cpp
remote/rtRemoteStreamSelector.cpp

Average rt remote message takes ~200-300 bytes, so touching 1MB is overhead in this case.
Instead, let rtReadMessage resize the buffer as required (capacity remains the same).

Reduce rss memory used by rtremote

---

src/rtFileDownloader.cpp
src/rtFileDownloader.h
src/rtHttpCache.cpp
src/rtHttpCache.h
tests/pxScene2d/test_imagecache.cpp

The existing code  allocates buffer for the full file and returning to application for use.
If the cached file is bigger file say 30 MB, it allocates for 30 MB and store the data for use.
Now added the provision to application to read it however it wants. Also there is no change in existing file reading machanics unless application sets setReadCachedDataInChunks.

Provided access to application to use the FilePointer to read the data in a smaller chunk.

---

src/wayland_egl/pxEventLoopNative.cpp

fixes the following lookup error while loading libservicemanager.so.1:
/usr/lib/libpxscene.so: error: symbol lookup error: undefined symbol: _Z6pxMainiPPc (fatal)

add possibility to resolve servicemanager dependencies

---

remote/rtRemoteEnvironment.cpp

In case of error in rtRemoteInit() the call "env->start();" may be executed many times.
The current implementation creates 4 worker threads for every unsuccessful call.
The total number of created worker threads may grow indefinitely.
This change limits the total number of created threads by the value kNumWorkers.

Limit the number of worker threads

---

src/unix/rtMutexNative.cpp
src/unix/rtMutexNative.h

Fixes the following data race:
WARNING: ThreadSanitizer: data race (pid=6652)
Write of size 1 at 0x7b3400000030 by thread T1:
#0 rtMutexNative::unlock() pxCore/src/unix/rtMutexNative.cpp:24 (pxscene+0x0000005954c3)
#1 rtThreadPoolNative::startThread() pxCore/src/unix/rtThreadPoolNative.cpp:83 (pxscene+0x000000595ba8)
#2 launchThread(void*) pxCore/src/unix/rtThreadPoolNative.cpp:9 (pxscene+0x0000005956a4)
#3 <null> <null> (libtsan.so.0+0x0000000257eb)
Previous write of size 1 at 0x7b3400000030 by main thread (mutexes: write M516):
#0 rtMutexNative::unlock() pxCore/src/unix/rtMutexNative.cpp:24 (pxscene+0x0000005954c3)
#1 rtThreadPoolNative::executeTask(rtThreadTask*) pxCore/src/unix/rtThreadPoolNative.cpp:99 (pxscene+0x000000595c60)
#2 pxTextureOffscreen::freeOffscreenDataInBackground() …

ThreadSanitizer: fix data race in rtMutexNative.cpp

---

src/rtScriptDuk/rtFunctionWrapper.cpp
src/rtScriptDuk/rtObjectWrapper.cpp
src/rtScriptDuk/rtScriptDuk.cpp
src/rtScriptNode/rtWrapperUtils.cpp

src/rtScriptDuk/rtScriptDuk.cpp:286:21: error: ‘exec_argv’ defined but not used [-Werror=unused-variable]
static const char** exec_argv;
^~~~~~~~~
src/rtScriptDuk/rtScriptDuk.cpp:285:12: error: ‘exec_argc’ defined but not used [-Werror=unused-variable]
static int exec_argc;
^~~~~~~~~
pxCore/src/rtScriptDuk/rtObjectWrapper.cpp:354:19: error: unused variable ‘obj_idx’ [-Werror=unused-variable]
duk_idx_t obj_idx = duk_push_object(ctx);
^~~~~~~
pxCore/src/rtScriptDuk/rtObjectWrapper.cpp: At global scope:
pxCore/src/rtScriptDuk/rtObjectWrapper.cpp:15:20: error: ‘kPropLength’ defined but not used [-Werror=unused-variable]
static const char* kPropLength = "length";
^~~~~~~~~~~ …

fix compilation errors -Werror=unused-variable

---

src/rtScriptNode/rtFunctionWrapper.h

Adds missing includes to fix errors like the following:
src/rtScriptNode/rtFunctionWrapper.h:96:8: error: ‘mutex’ in namespace ‘std’ does not name a type
std::mutex mMutex;
^~~~~
src/rtScriptNode/rtFunctionWrapper.h:97:8: error: ‘condition_variable’ in namespace ‘std’ does not name a type
std::condition_variable mCond;
^~~~~~~~~~~~~~~~~~

fix compilation error using -DUSE_STD_THREADS option

---

examples/pxScene2d/src/browser/editbox.js

The references were showing as undefined because they were not being
invoked with `this`.  This causes a bunch of log spam in the terminal.

Fix undefined reference to keepFocus and showFocus

---

examples/pxScene2d/src/rcvrcore/XModule.js

For some reason, the `appSandbox.importTracking[bPath]` is being
evaluated multiple times.  During the first pass, that whole object is
deleted, so on the second pass, it evaluates to undefined and the module
import can't finish.
I don't know exactly what is causing this problem, but this fix
re-enables things that ran under 0.35.0.x. The problem _might_ be
related to calling px.import multiple times from the same file, but
that's only a guess based on log output and what I suspect this module
might be for.

Fix double free error with sandbox imports

---

remote/rtRemote.cpp
remote/rtRemote.h

1. Implement rtRemoteShutdown() immediate (ignoring RefCount)
2. Do not start rtRemoteEnvironment if env->Server->open() failed

Implement rtRemoteShutdown immediate (ignoring RefCount)

---

examples/pxScene2d/src/pxContextGL.cpp

* issue with upper en lower border fixed
* issue with center border fixed
I noticed some issues in drawing those upper and lower borders, those were drawn by only 2 triangles so not fully filled. And when transparency was used, you could see some overlapping drawings in other parts of the borders..
By simplifying the drawing now by using less nodes (took it from drawRectOutline) and adding some extra nodes to also draw the inner center of the rectangle, my tests look OK now.

Fix drawing of border in drawImage9Border2

---

src/rtScriptDuk/rtObjectWrapper.cpp
src/rtScriptDuk/rtScriptDuk.cpp

pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In constructor ‘rtDukContext::rtDukContext()’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:182:9: error: ‘rtDukContext::mContextifyContext’ will be initialized after [-Werror=reorder]
void* mContextifyContext;
^~~~~~~~~~~~~~~~~~
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:170:29: error:   ‘duk_context* rtDukContext::dukCtx’ [-Werror=reorder]
duk_context              *dukCtx;
^~~~~~
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:327:1: error:   when initialized here [-Werror=reorder]
rtDukContext::rtDukContext() :
^~~~~~~~~~~~
pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In constructor ‘rtDukContext::rtDukContext(rtDukContextRef)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:182:9: error: ‘rtDukContext::mContextifyContext’ will be initialized after …

fix reorder compilation errors

---

remote/rtRemoteServer.cpp

pxCore/remote/rapidjson/document.h:508:13: error: ‘index’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
if (!(u & 0x80000000))
^~~~~~~~~~~~~~~~~
pxCore/remote/rtRemoteServer.cpp:760:17: note: ‘index’ was declared here
uint32_t    index;
^~~~~

fix maybe-uninitialized compilation error

---

src/rtScriptDuk/rtScriptDuk.cpp
src/rtScriptNode/rtScriptNode.cpp

pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In member function ‘virtual long unsigned int rtDukContext::Release()’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:1359:13: error: deleting object of polymorphic class type ‘rtDukContext’ which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
delete this;
^~~~
pxCore/src/rtScriptNode/rtScriptNode.cpp: In member function ‘virtual long unsigned int rtScriptNode::Release()’:
pxCore/src/rtScriptNode/rtScriptNode.cpp:961:13: error: deleting object of polymorphic class type ‘rtScriptNode’ which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
delete this;
^~~~

fix delete-non-virtual-dtor compilation errors

---

src/rtScriptDuk/rtScriptDuk.cpp

pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_require(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:643:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
};
^
pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_mod_resolve(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:740:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
};
^
pxCore/src/rtScriptDuk/rtScriptDuk.cpp: In function ‘duk_ret_t duv_mod_load(duk_context*)’:
pxCore/src/rtScriptDuk/rtScriptDuk.cpp:757:3: error: missing initializer for member ‘duv_schema_entry::checker’ [-Werror=missing-field-initializers]
};
^ …

fix missing-field-initializers compilation errors

---

tests/pxScene2d/pxscene2dtestsmain.cpp
tests/pxScene2d/test_pxUtil.cpp
tests/pxScene2d/test_rtZip.cpp

unused-but-set-variable errors:
-------------------------------
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘virtual void pxUtilTest::TearDown()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:102:12: error: variable ‘sysRet’ set but not used [-Werror=unused-but-set-variable]
bool sysRet;
^~~~~~
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadImage3ArgsPngSuccessTest()’:
pxCore/tests/pxScene2d/test_pxUtil.cpp:114:15: warning: unused variable ‘loadImageSuccess’ [-Wunused-variable]
rtError loadImageSuccess = rtLoadFile("supportfiles/status_bg.png", d);
^~~~~~~~~~~~~~~~
pxCore/tests/pxScene2d/test_pxUtil.cpp: In member function ‘void pxUtilTest::pxLoadPNGImage3ArgsCreateReadStructFailTest()’: …

fix unused-but-set-variable and unused-variable compilation errors

---

tests/pxScene2d/test_rtnode.cpp

Fixes the following warning:
pxCore/tests/pxScene2d/test_rtnode.cpp: In member function ‘virtual void pxScene2dTests_rtNodeTests_Test::TestBody()’:
pxCore/tests/pxScene2d/test_rtnode.cpp:192:21: warning: suggest parentheses around comparison in operand of ‘==’ [-Wparentheses]
EXPECT_TRUE( t2 < (t1 / 4) == true);
~~~^~~~~~~~~~
pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/include/gtest/internal/gtest-internal.h:1189:34: note: in definition of macro ‘GTEST_TEST_BOOLEAN_’
::testing::AssertionResult(expression)) \
^~~~~~~~~~
pxCore/tests/pxScene2d/test_rtnode.cpp:192:5: note: in expansion of macro ‘EXPECT_TRUE’
EXPECT_TRUE( t2 < (t1 / 4) == true);
^~~~~~~~~~~

fix parentheses compilation warning

---

tests/pxScene2d/test_pxMatrix4T.cpp

pxCore/tests/pxScene2d/test_pxMatrix4T.cpp:264:0: error: ignoring #pragma optimize  [-Werror=unknown-pragmas]
#pragma optimize( "", off )
pxCore/tests/pxScene2d/test_pxMatrix4T.cpp:269:0: error: ignoring #pragma optimize  [-Werror=unknown-pragmas]
#pragma optimize( "", on )

fix unknown-pragmas compilation errors

---

tests/pxScene2d/test_jsfiles.cpp

Fixes the following error:
pxCore/tests/pxScene2d/test_jsfiles.cpp:1:0: error: "ENABLE_RT_NODE" redefined [-Werror]
#define ENABLE_RT_NODE
<command-line>:0:0: note: this is the location of the previous definition

fix -Werror compilation errors

---

examples/pxScene2d/src/pxWayland.cpp

Fix for crash upon going to standby or shutdown, caused by pxWayland::launchAndMonitorClient running in another thread and using the freed context pointer. The per-cautionary checks within the Westeros routines seems to don't because the pointer is not zero.

Fix for crash in pxWayland::launchAndMonitorClient

---

examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h

Fixes the following data race:
WARNING: ThreadSanitizer: data race (pid=10382)
Write of size 1 at 0x7b44001817aa by thread T31 (mutexes: write M68656):
#0 pxWayland::connectToRemoteObject() pxCore/examples/pxScene2d/src/pxWayland.cpp:713 (pxscene+0x00000058ea65)
#1 pxWayland::findRemoteThread(void*) pxCore/examples/pxScene2d/src/pxWayland.cpp:643 (pxscene+0x00000058e625)
#2 <null> <null> (libtsan.so.0+0x0000000257eb)
Previous write of size 1 at 0x7b44001817aa by main thread (mutexes: write M357):
#0 pxWayland::terminateClient() pxCore/examples/pxScene2d/src/pxWayland.cpp:579 (pxscene+0x00000058e2c4)
#1 pxWayland::~pxWayland() pxCore/examples/pxScene2d/src/pxWayland.cpp:94 (pxscene+0x00000058bd42)
#2 pxWayland::~pxWayland() pxCore/examples/pxScene2d/src/pxWayland.cpp:96 …

ThreaddSanitizer: fix data race pxWayland(mWaitingForRemoteObject)

---

src/pxUtil.cpp

Fixex attempt to allocate 0xffffffff833db0fe bytes of data:
==18628==WARNING: AddressSanitizer failed to allocate 0xffffffff833db0fe bytes
==18628==AddressSanitizer CHECK failed: ../../../../libsanitizer/sanitizer_common/sanitizer_allocator.cc:218 "((0)) != (0)" (0x0, 0x0)
#0 0x7f939d46a902  (/lib64/libasan.so.4+0xe9902)
#1 0x7f939d489295 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/lib64/libasan.so.4+0x108295)
#2 0x7f939d470042  (/lib64/libasan.so.4+0xef042)
#3 0x7f939d3a8b46  (/lib64/libasan.so.4+0x27b46)
#4 0x7f939d45f81a in malloc (/lib64/libasan.so.4+0xde81a)
#5 0x81fc71 in pxLoadJPGImageTurbo(char const*, unsigned long, pxOffscreen&) pxCore/src/pxUtil.cpp:711
#6 0x81dea4 in pxLoadImage(char const*, unsigned long, pxOffscreen&) …

AddressSanitizer: fix allocating too big buffers (libjpeg-turbo)

---

examples/pxScene2d/src/pxScene2d.cpp
tests/pxScene2d/test_screenshot.cpp

Fixes the followg memory overflow eror:
==14924==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000114f2f at pc 0x7f9a07e6aed2 bp 0x7fff38e88bb0 sp 0x7fff38e88ba0
READ of size 1 at 0x602000114f2f thread T0
#0 0x7f9a07e6aed1 in base64_decode(unsigned char const*, unsigned long, unsigned long*) pxCore/examples/pxScene2d/src/pxScene2d.cpp:345
#1 0x627b36 in screenshotTest::test_base64_encode_decode() pxCore/tests/pxScene2d/test_screenshot.cpp:60
#2 0x627b36 in screenshotTest_screenshotTests_Test::TestBody() pxCore/tests/pxScene2d/test_screenshot.cpp:183
#3 0x80ccbe in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest …

AddressSanitizer: fix heap-buffer-overflow (caused by base64_decode())

---

tests/pxScene2d/test_imagecache.cpp

Fixes the following heap-use-after-free crash:
==21739==ERROR: AddressSanitizer: heap-use-after-free on address 0x61400003c8f1 at pc 0x000000825f62 bp 0x7fffc21a8990 sp 0x7fffc21a8980
READ of size 1 at 0x61400003c8f1 thread T0
#0 0x825f61 in rtFileDownloadRequest::isDataCached() /home/sw/projects/pxscene/pxCore/src/rtFileDownloader.cpp:366
#1 0x665424 in rtFileDownloaderTest::disableCacheTest() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/test_imagecache.cpp:893
#2 0x64dd3b in rtFileDownloaderTest_checkCacheTests_Test::TestBody() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/test_imagecache.cpp:1229
#3 0x7ad278 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) …

AddressSanitizer: fix heap-use-after-free crash in disableCacheTest()

---

src/rtValue.cpp

Fixes the following error:
pxCore/src/rtValue.cpp: In member function ‘rtError rtValue::getBool(bool&) const’:
pxCore/src/rtValue.cpp:302:7: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
if (mValue.stringValue)
^~
pxCore/src/rtValue.cpp:303:51: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
v = (*mValue.stringValue=="")?false:true; break;
^~~~~

fix misleading-indentation compilation error

---

src/rtFile.cpp
src/rtFile.h
src/rtFileDownloader.cpp
src/rtFileDownloader.h
tests/pxScene2d/CMakeLists.txt
tests/pxScene2d/test_api.cpp
tests/pxScene2d/test_imagecache.cpp
tests/pxScene2d/test_jsfiles.cpp
tests/pxScene2d/test_memoryleak.cpp
tests/pxScene2d/test_rtError.cpp

Excerpt of fixed issues:
pxCore/tests/pxScene2d/test_api.cpp:40:44: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
startJsFile("onescene_with_parent.js");
^
make[2]: *** [tests/pxScene2d/CMakeFiles/pxscene2dtests.dir/build.make:111: tests/pxScene2d/CMakeFiles/pxscene2dtests.dir/test_api.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
pxCore/tests/pxScene2d/test_memoryleak.cpp: In member function ‘void pxSceneContainerLeakTest::withParentRemovedGCNotHappenedTest()’:
pxCore/tests/pxScene2d/test_memoryleak.cpp:36:44: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
startJsFile("onescene_with_parent.js");
^
pxCore/tests/pxScene2d/test_memoryleak.cpp: In …

fix write-strings compilation errors

---

src/pxUtil.cpp

pxCore/src/pxUtil.cpp: In function ‘rtError pxLoadPNGImage(const char*, size_t, pxOffscreen&)’:
pxCore/src/pxUtil.cpp:948:11: error: variable ‘e’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
rtError e = RT_FAI

fix 'clobbered' compilation errors

---

examples/pxScene2d/src/CMakeLists.txt
src/pxMatrix4T.cpp

Backtrace before (note that it causes stack-overflow):
(gdb) bt
#0  sincosf (x=-6.16183472, s=s@entry=0x7fffd382066c, c=c@entry=0x7fffd3820668) at pxCore/src/pxMatrix4T.cpp:28
#1  0x00000000004d0a5b in sincosf (x=<optimized out>, s=s@entry=0x7fffd382069c, c=c@entry=0x7fffd3820698) at pxCore/src/pxMatrix4T.cpp:28
#2  0x00000000004d0a5b in sincosf (x=<optimized out>, s=s@entry=0x7fffd38206cc, c=c@entry=0x7fffd38206c8) at pxCore/src/pxMatrix4T.cpp:28
#3  0x00000000004d0a5b in sincosf (x=<optimized out>, s=s@entry=0x7fffd38206fc, c=c@entry=0x7fffd38206f8) at pxCore/src/pxMatrix4T.cpp:28
#4  0x00000000004d0a5b in sincosf (x=<optimized out>, s=s@entry=0x7fffd382072c, c=c@entry=0x7fffd3820728) at pxCore/src/pxMatrix4T.cpp:28
#5  0x00000000004d0a5b in sincosf (x=<optimized out>, …

prefer to use built-in versions of sincos() and sincosf()

---

appveyor.yml
ci/appveyor-custodian.bat
ci/appveyor-custodian.py
ci/build_win32.bat

Adds Appveyor-custodian script which manages number of builds
to make sure we will not exceed available quota.
To use it with AppVeyro CI infrastructure please add in:
Projects->Settings->Environment->Environment variables
API_TOKEN variable.
Token can be found on API token page under your AppVeyor account.

add AppVeyor artifacts management

---

tests/pxScene2d/test_imagecache.cpp

We had to remove this test:
void downloadedDataTest()
{
rtFileCache::instance()->clearCache();
addDataToCache("http://fileserver/file.jpeg",getHeader(),getBodyData(),fixedData.length());
rtFileDownloadRequest* request = new rtFileDownloadRequest("http://fileserver/file.jpeg",this);
expectedStatusCode = 0;
expectedCachePresence = true;
expectedHttpCode = 200;
(1)   rtFileDownloader::instance()->downloadFile(request);
char *data = new char [1000];
size_t size = 0;
memset (data, 0, 1000);
(2)   request->downloadedData(data, size);
//since the data would have been consumed by callback
EXPECT_TRUE (size == 0);
delete[] data;
sem_wait(testSem);
}
Because it is not possible to invoke (2) after (1) has finished
('request' is being deleted in the end of downloadFile() method).
This is where it …

AddressSanitizer: fix heap-use-after-free in downloadedDataTest()

---

src/wayland_egl/pxWindowNative.cpp

Detected by the following compiler error:
pxCore/src/wayland_egl/pxWindowNative.cpp:297:1: error: missing initializer for member ‘wl_shell_surface_listener::popup_done’ [-Werror=missing-field-initializers]
};
^

remove unused code (wayland_egl / shell_surface_listener)

---

examples/pxScene2d/src/pxFont.cpp
examples/pxScene2d/src/pxImage9Border.h
examples/pxScene2d/src/pxRectangle.h
examples/pxScene2d/src/pxText.h

Excerpt of fixed issues:
In file included from pxCore/examples/pxScene2d/src/pxScene2d.h:41:0,
from pxCore/examples/pxScene2d/src/pxRectangle.h:24,
from pxCore/examples/pxScene2d/src/pxRectangle.cpp:21:
pxCore/examples/pxScene2d/src/../../../src/rtValue.h: In member function ‘rtError pxRectangle::fillColor_PropGetterThunk(rtValue&) const’:
pxCore/examples/pxScene2d/src/../../../src/rtValue.h:237:56: error: ‘pv’ is used uninitialized in this function [-Werror=uninitialized]
void asn(uint32_t v)                      { setUInt32(v);   }
~~~~~~~~~^~~
In file included from pxCore/examples/pxScene2d/src/../../../src/rtObject.h:29:0,
from pxCore/examples/pxScene2d/src/pxScene2d.h:42,
from pxCore/examples/pxScene2d/src/pxRectangle.h:24,
from pxCore/examples/pxScene2d/src/pxRectangle.cpp:21: …

fix 'uninitialized' & 'maybe-uninitialized' compilation errors

---

src/rtScriptNode/rtScriptNode.cpp

Fixes the following issue:
src/rtScriptNode/rtScriptNode.cpp:404:46: error: ignoring return value of 'char* getcwd(char*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
|        getcwd(currentPath,sizeof(currentPath));
^

fix 'unused-result' compilation error

---

src/rtFileCache.cpp
src/rtHttpCache.cpp
src/rtHttpCache.h

LSA Ad Cache telemetry requires to print cache expiration print along with Url, filename and size.

LSA Ad Cache telemetry requires to print cache expiration print.

---

examples/pxScene2d/src/rasterizer/pxRasterizer.cpp

Compiler output:
pxCore/examples/pxScene2d/src/rasterizer/xs_code/xs_Float.h: In function ‘int32 xs_CRoundToInt(real64, real64)’:
pxCore/examples/pxScene2d/src/rasterizer/xs_code/xs_Float.h:349:33: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
return ((int32*)&val)[_xs_iman_];
^
Note: The 'xs_code' seems to be complete broken e.g.
typedef long uint32; // <- uint32 will not have 32-bits on x86-64!!!
then uses something like the following:
double val;
return ((int32*)&val)[1]; // <- on 64-bit Big Endian platforms it will read random memory
thus it seems to be simpler to not use 'xs_code' at all.
The fix adds XS_CODE_ENABLED which, by default do not use implementation
from 'xs_code' and, provides equivalent implementation of two function …

fix 'strict-aliasing' compilation errors and typo in pxClamp usage

---

examples/pxScene2d/src/pxScene2d.h

Fixes the following compilation errors:
pxCore/examples/pxScene2d/src/pxScene2d.h: In constructor ‘pxScene2d::pxScene2d(bool, pxScriptView*)’:
pxCore/examples/pxScene2d/src/pxScene2d.h:1624:10: error: ‘pxScene2d::mLastFrameDirtyRect’ will be initialized after [-Werror=reorder]
pxRect mLastFrameDirtyRect;
^~~~~~~~~~~~~~~~~~~
pxCore/examples/pxScene2d/src/pxScene2d.h:1621:8: error:   ‘bool pxScene2d::mDirty’ [-Werror=reorder]
bool mDirty;
^~~~~~
pxCore/examples/pxScene2d/src/pxScene2d.cpp:1748:1: error:   when initialized here [-Werror=reorder]
pxScene2d::pxScene2d(bool top, pxScriptView* scriptView)
^~~~~~~~~

fix error reorder when PX_DIRTY_RECTANGLES is enabled

---

remote/rtRemoteSocketUtils.cpp

pxCore/remote/rtRemoteSocketUtils.cpp:551:57: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
int count = snprintf(buff, n, kUnixSocketTemplate, pid);

fix 'format-nonliteral' compilation error

---

examples/pxScene2d/src/pxImage.cpp
examples/pxScene2d/src/pxImage9.cpp
examples/pxScene2d/src/pxImage9Border.cpp
examples/pxScene2d/src/pxImageA.cpp
examples/pxScene2d/src/pxResource.cpp
examples/pxScene2d/src/pxResource.h

checkStretchX/Y should be protected by null checks, but it's too soon to try calling them in setResource.

Do not call checkStretch in setResource

---

remote/rtRemoteConfigGen.cpp

pxCore/remote/rtRemoteConfigGen.cpp:168:10: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
return std::move(configItems);
^

fix 'pessimizing-move' compiler errors

---

src/essos/pxWindowNative.cpp

Compiler output:
pxCore/src/essos/pxWindowNative.cpp: In static member function ‘static void pxWindowNative::runEventLoop()’:
pxCore/src/essos/pxWindowNative.cpp:478:19: error: unused variable ‘eDisplay’ [-Werror=unused-variable]
essosDisplay* eDisplay = dRef.getDisplay();
^~~~~~~~

fix error: unused variable ‘eDisplay’

---

examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/pxText.h
examples/pxScene2d/src/pxTextBox.h
src/rtObject.h
tests/pxScene2d/test_pxImage.cpp

Log excerpt:
In file included from pxCore/examples/pxScene2d/src/pxScene2d.h:42:0,
from pxCore/examples/pxScene2d/src/pxFont.h:31,
from pxCore/examples/pxScene2d/src/pxFont.cpp:22:
pxCore/examples/pxScene2d/src/../../../src/rtObject.h:315:19: error: ‘virtual rtError rtObject::Set(uint32_t, const rtValue*)’ was hidden [-Werror=overloaded-virtual]
virtual rtError Set(uint32_t /*i*/, const rtValue* /*value*/);
^~~
In file included from pxCore/examples/pxScene2d/src/pxFont.cpp:24:0:
pxCore/examples/pxScene2d/src/pxText.h:75:19: error:   by ‘virtual rtError pxText::Set(const char*, const rtValue*)’ [-Werror=overloaded-virtual]
virtual rtError Set(const char* name, const rtValue* value)
^~~
make[2]: *** …

fix 'overloaded-virtual' compilation errors

---

src/rtObject.cpp

Fixes:
pxCore/src/rtObject.cpp: In member function ‘rtError rtEmit::delListener(const char*, rtIFunction*)’:
pxCore/src/rtObject.cpp:98:7: error: unused variable ‘i’ [-Werror=unused-variable]
int i = 0;
^

fix error: unused variable ‘i’

---

src/rtFileDownloader.cpp

Fixes:
In function ‘void rtFileDownloadRequest::setHTTPError(const char*)’,
inlined from ‘void rtFileDownloadRequest::setHTTPError(const char*)’:
src/rtFileDownloader.cpp:423:12: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 256 equals destination size [-Werror=stringop-truncation]
strncpy(mHttpErrorBuffer, httpError, CURL_ERROR_SIZE);
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

fix -Werror=stringop-truncation compilation error

---

src/rtScriptNode/rtScriptNode.cpp

fixes the crash when tracing controller wasn't initialized:
Thread 1 "pxscene" received signal SIGSEGV, Segmentation fault.
0x00007fc0537acb76 in node::GetCategoryGroupEnabled (category_group=0x7b080000cba0 "node.async_hooks") at ../src/node_trace_events.cc:22
(gdb) bt
#0  0x00007fc0537acb76 in node::GetCategoryGroupEnabled (category_group=0x7b080000cba0 "node.async_hooks") at ../src/node_trace_events.cc:22
#1  0x00007fc0537acf33 in node::CategoryGroupEnabled (args=...) at ../src/node_trace_events.cc:131
#2  0x00007fc053924322 in v8::internal::FunctionCallbackArguments::Call (this=this@entry=0x7ffcdfdbeb70, f=f@entry=0x7fc0537acef0 <node::CategoryGroupEnabled(v8::FunctionCallbackInfo<v8::Value> const&)>) at ../deps/v8/src/api-arguments.cc:25
#3  0x00007fc05398dfb6 in …

add support for node8 (>v8.9.0) (tracing-controller fix)

---

src/wayland_egl/pxWindowNative.cpp

- correct poll() usage,
- do not sleep in poll(),
- handle EINTR properly.

fix for PXCORE_WAYLAND_DISPLAY_READ_EVENTS=ON

---

src/wayland_egl/pxWindowNative.cpp

Fixes the following crash (also observed on Broadcom Nexus implementation):
ASAN:DEADLYSIGNAL
=================================================================
==31533==ERROR: AddressSanitizer: SEGV on unknown address 0x7febe91f7148 (pc 0x7febe91f972c bp 0x7ffd07589280 sp 0x7ffd07589248 T0)
==31533==The signal is caused by a WRITE memory access.
#0 0x7febe91f972b in wl_egl_window_resize (/lib64/libwayland-egl.so.1+0x72b)
#1 0x66c9d4 in shell_surface_configure src/wayland_egl/pxWindowNative.cpp:295
#2 0x7febe3f0ed1d in ffi_call_unix64 (/lib64/libffi.so.6+0x5d1d)
#3 0x7febe3f0e68e in ffi_call (/lib64/libffi.so.6+0x568e)
#4 0x7febe8ff2d8a  (/lib64/libwayland-client.so.0+0x8d8a)
#5 0x7febe8fef927  (/lib64/libwayland-client.so.0+0x5927)
#6 0x7febe8ff0be3 in wl_display_dispatch_queue_pending …

fix SIGSEGV in wl_egl_window_resize()

---

examples/pxScene2d/src/pxContextGL.cpp

Fixes:
examples/pxScene2d/src/pxContextGL.cpp:3116:47: error: unused parameter 'bytesRequested' [-Werror,-Wunused-parameter]
int64_t pxContext::ejectTextureMemory(int64_t bytesRequested, bool forceEject)
^
examples/pxScene2d/src/pxContextGL.cpp:3116:68: error: unused parameter 'forceEject' [-Werror,-Wunused-parameter]
int64_t pxContext::ejectTextureMemory(int64_t bytesRequested, bool forceEject)
^

fix -Wunused-parameter errors when ENABLE_LRU_TEXTURE_EJECTION is undefined

---

src/pxUtil.cpp

Fixes the following issue:
=================================================================
==12472==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete) on 0x602000057c90
#0 0x7fef91d40748 in operator delete(void*) (/lib64/libasan.so.5+0xf1748)
#1 0xa67017 in pxLoadSVGImage(char const*, unsigned long, pxOffscreen&, int, int)
pxLoadSVGImage(char const*, unsigned long, pxOffscreen&, int, int) /home/sw/projects/pxscene/pxCore/src/pxUtil.cpp:1005
#2 0xa6879b in pxLoadImage(char const*, unsigned long, pxOffscreen&, int, int) /home/sw/projects/pxscene/pxCore/src/pxUtil.cpp:106
#3 0x6bc75b in pxUtilTest::pxLoadImage3ArgsLessLengthFailureTest() /home/sw/projects/pxscene/pxCore/tests/pxScene2d/test_pxUtil.cpp:160
#4 0x6bc75b in pxUtilTest_pxutilsTest_Test::TestBody() …

fix AddressSanitizer: alloc-dealloc-mismatch error (fixes #1227)

---

examples/pxScene2d/src/pxScene2d.cpp

Fixes:
examples/pxScene2d/src/pxScene2d.cpp: In member function ‘rtError pxSceneContainer::setServiceContext(rtObjectRef)’:
examples/pxScene2d/src/pxScene2d.cpp:3703:3: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
if( !mInitialized)
^~
examples/pxScene2d/src/pxScene2d.cpp:3704:26: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
mServiceContext = o; return RT_OK;
^~~~~~

fix for -Werror=misleading-indentation compilation errors

---

src/pxUtil.cpp

Fixes the following issue:
=================================================================
==9455==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete) on 0x60c000000280
#0 0x7f34c8e29748 in operator delete(void*) (/lib64/libasan.so.5+0xf1748)
#1 0x7f34c35cf66b in __run_exit_handlers /usr/src/debug/glibc-2.27-56-g50df56ca86/stdlib/exit.c:108
#2 0x7f34c35cf79b in __GI_exit /usr/src/debug/glibc-2.27-56-g50df56ca86/stdlib/exit.c:139
#3 0x7f34c7409e63 in Exit ../src/node.cc:2472
#4 0x7f34c75e5059 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ../deps/v8/src/api-arguments.cc:25
#5 0x7f34c764ddcf in HandleApiCallHelper<false> ../deps/v8/src/builtins/builtins-api.cc:112
#6 0x7f34c764e4a6 in …

fix AddressSanitizer: alloc-dealloc-mismatch in ~NSVGrasterizerEx()

---

src/rtObject.cpp

Fixes the following issues:
src/rtObject.cpp:74:65: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
if (e.n == eventName && ((e.f.getPtr() == f) || ((f->hash() != -1) && (e.fnHash == f->hash()))) && !e.isProp)
~~~~~~~~~ ^  ~~
src/rtObject.cpp:103:58: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
if (e.n == eventName && ((e.f.getPtr() == f) || ((-1 != e.fnHash) && (e.fnHash == f->hash()))) && !e.isProp)
~~ ^  ~~~~~~~~

fix '-Werror,-Wsign-compare' compilation errors

---

src/pxUtil.cpp

Fixes error at: pxscene/pxCore/src/pxUtil.cpp:1479:1: error: control reaches end of non-void function [-Werror=return-type]

fix error: control reaches end of non-void function -Werror=return-type

---

src/rtObject.cpp

Fix bug caused by commit:
a969b568
All members of the entry were not being initialized when
calling setListener causing undefined behaviour like all
entries being deleted after the first call to emit send.

Fix _rtEmitEntry intilization bug

---

examples/pxScene2d/src/pxScene2d.cpp

Reject the animation promises, when invoked on object after dispose. Else, no promise object is created and js file is accessing then method on empty object. This is causing js file to hung and all the opened variables in that js file to get leaked.

Reject promise when animation is invoked after dispose

---

examples/pxScene2d/src/pxScene2d.cpp

Fixes:
pxCore/examples/pxScene2d/src/pxScene2d.cpp:149:13: error: ‘gWaylandAppsConfigLoaded’ defined but not used [-Werror=unused-variable]
static bool gWaylandAppsConfigLoaded = false;
^~~~~~~~~~~~~~~~~~~~~~~~

fix error: ‘gWaylandAppsConfigLoaded’ defined but not used

---

examples/pxScene2d/src/pxScene2d.cpp

Existing tests already cover this scenario.

Make move a no op if child is already in that position

---

src/rtError.h
src/rtObject.cpp
tests/pxScene2d/test_jsfiles.cpp

tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/include/gtest/gtest.h:1392:11: error: comparison of integers of different signs: 'const unsigned int' and 'const int' [-Werror,-Wsign-compare]
if (lhs == rhs) {
~~~ ^  ~~~
tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/include/gtest/gtest.h:1421:12: note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<unsigned int, int>' requested here
return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
^
tests/pxScene2d/test_api.cpp:84:7: note: in instantiation of function template specialization 'testing::internal::EqHelper<false>::Compare<unsigned int, int>' requested here
EXPECT_EQ(err1, RT_ERROR_INVALID_ARG);
^ …

fix -Wsign-compare (and some of -Wunused-parameter) errors

---

tests/pxScene2d/test_cors.cpp

Two issues seen here:
1,We are allocating the amount of memory same as content length and extra memory for '\0' not got allocated and so during strcpy, null character allocation is creating problem. 
2,Later on end of test, request variable will go out of scope and it's destruction will delete header data with free() call. Since memory is allocated with new, but clearance is happening with free, allo-dealloc mismatch error came from sanitizer.
Addressed above two problems as part of this change.

Fix sanitizer issues with test_cors

---

tests/pxScene2d/test_screenshot.cpp

Fixes the following issue:
In file included from /home/dw/projects/pxscene/pxCore/tests/pxScene2d/test_includes.h:32,
from /home/dw/projects/pxscene/pxCore/tests/pxScene2d/test_screenshot.cpp:25:
/home/dw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]’:
/home/dw/projects/pxscene/pxCore/tests/pxScene2d/../../examples/pxScene2d/external/gtest/googletest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long …

fix compilation error: 'error: comparison of integer expressions'

---

examples/pxScene2d/src/pxScene2d.cpp

pxCore/examples/pxScene2d/src/pxScene2d.cpp: In static member function ‘static rtError pxScriptView::printFunc(int, const rtValue*, rtValue*, void*)’:
pxscene/pxCore/examples/pxScene2d/src/pxScene2d.cpp:3941:19: error: unused variable ‘v’ [-Werror=unused-variable]
pxScriptView* v = (pxScriptView*)ctx;
^
and
pxCore/examples/pxScene2d/src/pxScene2d.cpp:3935:76: error: unused parameter 'result' [-Werror,-Wunused-parameter]
rtError pxScriptView::printFunc(int numArgs, const rtValue* args, rtValue* result, void* ctx)
^
1 error generated.

fix error: unused variable ‘v’ and parameter 'result'

---

examples/pxScene2d/src/pxWayland.cpp

Good example of this is WPELauncher. In the initial code the PID of the
last received status update is stored as the ClientPID. So only this process
gets killed on a destroy call.

Wayland container should be able to support processes spawning sub processes

---

examples/pxScene2d/src/CMakeLists.txt
examples/pxScene2d/src/Spark.cpp
examples/pxScene2d/src/pxArchive.cpp
examples/pxScene2d/src/pxFont.cpp
examples/pxScene2d/src/pxResource.cpp
src/rtPathUtils.cpp
src/rtPathUtils.h
src/rtScriptDuk/rtScriptDuk.cpp
src/rtScriptV8/rtScriptNode.cpp
tests/pxScene2d/CMakeLists.txt
tests/pxScene2d/test_rtPathUtils.cpp

Allow NODE_PATH environment variable to contain multiple directories
separated by:
- ';' on windows platform,
- ':' on any other.
Notes:
- The first entry in NODE_PATH is used to load SANDBOX_JS file
(this preserves backward compatibility).
- If NODE_PATH is not defined then the default value is obtained
from getcwd(3).

local access file - 2nd generation

---

examples/pxScene2d/src/pxScene2d.cpp

Fixes the following error:
In file included from /home/runner/pxCore/examples/pxScene2d/src/pxScene2d.cpp:21:
pxCore/exmples/pxScene2d/src/pxScene2d.h: In constructor ‘pxScene2d::pxScene2d(bool, pxScriptView*)’:
pxCore/examples/pxScene2d/src/pxScene2d.h:1710:10: error: ‘pxScene2d::mLastFrameDirtyRect’ will be initialized after [-Werror=reorder]
pxRect mLastFrameDirtyRect;
^~~~~~~~~~~~~~~~~~~
pxCore/examples/pxScene2d/src/pxScene2d.h:1702:15: error:   ‘rtObjectRef pxScene2d::mArchive’ [-Werror=reorder]
rtObjectRef mArchive;
^~~~~~~~
pxCore/examples/pxScene2d/src/pxScene2d.cpp:1815:1: error:   when initialized here [-Werror=reorder]
pxScene2d::pxScene2d(bool top, pxScriptView* scriptView)
^~~~~~~~~

fix initialization order error (mLastFrameDirtyRect, mArchive)

---

src/pxUtil.cpp
src/rtHttpCache.cpp

'nanosvg' performs a destructive parse to the SVG source buffer.  
Passing it a working copy prevents the destruction propagating elsewhere (e.g. into the cache)

Fix for SVG caching bug.

---

src/rtFileDownloader.cpp
src/rtFileDownloader.h
tests/pxScene2d/test_imagecache.cpp

1. Added return size of executeDownloadProgressCallback in WriteMemoryCallback
2. Handled defer cache read() functionality in downloadFile

DELIA-28961 : Fixing the issue reported in DELIA-28961, for LSA AD cache with back to back ad insertion.

---

src/rtFileDownloader.cpp

Fixes the followin compilation error:
In file included from pxCore/src/rtFileDownloader.cpp:24:
pxCore/src/rtFileDownloader.h: In constructor ‘rtFileDownloadRequest::rtFileDownloadRequest(const char*, void*, void (*)(rtFileDownloadRequest*))’:
pxCore/src/rtFileDownloader.h:138:8: error: ‘rtFileDownloadRequest::mUseCallbackDataSize’ will be initialized after [-Werror=reorder]
bool mUseCallbackDataSize;
^~~~~~~~~~~~~~~~~~~~
pxCore/src/rtFileDownloader.h:115:9: error:   ‘void* rtFileDownloadRequest::mDownloadProgressUserPtr’ [-Werror=reorder]
void *mDownloadProgressUserPtr;
^~~~~~~~~~~~~~~~~~~~~~~~
pxCore/src/rtFileDownloader.cpp:159:1: error:   when initialized here [-Werror=reorder]
rtFileDownloadRequest::rtFileDownloadRequest(const char* imageUrl, void* callbackData, void …

fix reorder error (mUseCallbackDataSize, mDownloadProgressUserPtr)

---

remote/rtRemoteFunction.cpp
remote/rtRemoteValueWriter.cpp
src/rtObject.h

Now every time client makes a call to delListener(), rtFunctionRef() gets new ID and server doesn't identify it when it matches it with the stored handlers.
This change will ensure at client rtFuncionRef stores the id after creation and refers that hence forth instead of creating new one everytime. And at the server side, the received
id (i.e. 'func://<uid>') is used to calculate a hash which is then used for add / del listeners

Fix broken addListener() & delListener() handling.

---

ci/builds/0499-clean.sh
ci/builds/0500-wayland-v8-gcc-tsan.sh
ci/builds/common.sh
cmake/CommDeps.cmake
cmake/V8Deps.cmake
src/rtScriptV8/rtScriptV8.cpp

It also fixes compilation errors when SUPPORT_V8 is defined.
Recommended options for compiling with 'v8' JS engine:
-DPREFER_SYSTEM_LIBRARIES=ON
-DSUPPORT_V8=ON
-DSUPPORT_NODE=OFF
-DSUPPORT_DUKTAPE=OFF
-DPKG_CONFIG_DISABLE_NODE=ON
-DPKG_CONFIG_DISABLE_NODE8=ON
For more comprehensive example please have a look at:
ci/builds/*-wayland-v8-gcc-tsan.sh script.

Add PREFER_SYSTEM_LIBRARIES support for 'v8' engine

---

ci/builds/ci-semaphoreci.sh
ci/builds/ci-travis.sh
ci/builds/test-testrunner.sh

- recommend by default to use 'Docker v1807' image,
- make it also works with Docker v1809 (release candidate) image,
- unset DISPLAY (as it's fake on semaphoreci),
- don't rely on external xvfb (use our own).

Update to the latest semaphoreci 'Docker v1807' image

---

src/rtHttpResponse.cpp

Fixes the following error:
/home/runner/pxCore/src/rtHttpResponse.h: In constructor ‘rtHttpResponse::rtHttpResponse()’:
/home/runner/pxCore/src/rtHttpResponse.h:63:13: error: ‘rtHttpResponse::mEmit’ will be initialized after [-Werror=reorder]
rtEmitRef mEmit;
^~~~~
/home/runner/pxCore/src/rtHttpResponse.h:59:11: error:   ‘int32_t rtHttpResponse::mStatusCode’ [-Werror=reorder]
int32_t mStatusCode;
^~~~~~~~~~~
/home/runner/pxCore/src/rtHttpResponse.cpp:31:1: error:   when initialized here [-Werror=reorder]
rtHttpResponse::rtHttpResponse()
^~~~~~~~~~~~~~

Fix rtHttpResponse::{mEmit,mStatusCode} reorder compilation error

---

src/rtHttpRequest.cpp
src/rtHttpResponse.cpp
src/rtObject.cpp
src/rtObject.h
tests/pxScene2d/test_rtHttpRequest.cpp
tests/pxScene2d/test_rtHttpResponse.cpp

* tests for rtHttpRequest
* tests for rtHttpResponse
* new methods for rtEmit: clearListeners by event name, 'once' listeners
* fix for rtHttpRequest: emit 'error' instead of 'response' in case error set

tests and fixes for rtHttp* listeners:

---

examples/pxScene2d/src/glut/pxContextUtils.cpp
examples/pxScene2d/src/pxTextBox.cpp

/home/npoltorapavlo/pxCore/examples/pxScene2d/src/pxTextBox.cpp:277:52: error: no matching function for call to ‘pxMax(float&, int)’
return pxMax(mw, abs(bounds->x2()-bounds->x1()));
^
/home/npoltorapavlo/pxCore/examples/pxScene2d/src/glut/pxContextUtils.cpp:21:37: warning: unused parameter ‘id’ [-Wunused-parameter]
pxError deleteInternalGLContext(int id)
^

build fix:

---

src/rtFileCache.cpp
src/rtFileDownloader.cpp
src/rtFileDownloader.h
src/rtHttpCache.cpp
src/rtString.cpp
src/rtString.h
tests/pxScene2d/test_imagecache.cpp

CDN requires the curl download request to be less range or equal to (7 * 47 * 4096). So added support for multiple call call with chunk request instead of single bigger download.

Added support for byte range curl download(RDK-24363).

---

examples/pxBenchmark/src/CMakeLists.txt
examples/pxScene2d/src/CMakeLists.txt
examples/pxScene2d/src/Makefile_MT
examples/pxScene2d/src/pxFont.cpp
examples/pxScene2d/src/pxFont.h
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/pxTextCanvas.cpp
examples/pxScene2d/src/pxTextCanvas.h
tests/pxScene2d/test_pxTextCanvas.js

Implemented properties:
fillStyle
width
height
label
colorMode
Implemented methods:
measureText
fillText
translate
Stubs for:
textBaseline
globalAlpha
fillRect
shadowColor
shadowBlur
shadowOffsetX
shadowOffsetY
Demo app: https://github.com/sergiygladkyy/sparkTextCanvas
```
git clone
npm i
npm run release-spark
cd dist/spark
npm i
Then run dist/spark/lightning-demo-spark.js
```
See also the following files in the src dir:
```
test-textcanvas.js - CI test
textcanvas-spark-min.js - minimal textCanvas invocation
textcanvas-spark.js - non-lightning textCanvas demo
```
Related repos with the updates for node modules:
wpe-lightning-sdk: https://github.com/sergiygladkyy/Lightning-SDK
wpe-lightning: https://github.com/sergiygladkyy/Lightning
wpe-lightning-spark: …

pxTextCanvas initial support

---

examples/pxScene2d/src/pxConstants.h
examples/pxScene2d/src/pxTextCanvas.cpp
examples/pxScene2d/src/pxTextCanvas.h

pxTextCanvas textAlignment and textBaseline support.
Allowed negative x and y coords in fillText() and fillRect().
Clipping is on by default to resemple HTML Canvas.
globalAlpha property

pxTextCanvas improvements

---

src/rtFileDownloader.cpp

Mutex lock/unlock is not required during reaching from cache.

Mutex lock/unlock is not required during reaching from cache.

---

examples/pxScene2d/src/CMakeLists.txt
src/CMakeLists.txt

-fpermissive is not accepted by latest version of Coverity.  Removing it for linux.

turn off permissive

---

examples/pxScene2d/src/pxFont.cpp
examples/pxScene2d/src/pxFont.h
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxText.cpp
examples/pxScene2d/src/pxTextCanvas.cpp
examples/pxScene2d/src/pxTextCanvas.h

pxTextCanvas: support for CutSx, CutSy, CutEx, CutEy, fontStyle in Lightning++

---

examples/pxScene2d/src/pxVideo.cpp
examples/pxScene2d/src/pxVideo.h

To properly close the playback when Spark app is restarted the following code should be added
scene.on("onClose", function(e) {
videoObject.stop();
});

Moved playback init/deinit from constructor/destructor to play/stop

---

src/essos/pxTimerNative.cpp
src/gles/pxTimerNative.cpp
src/glut/pxTimerNative.cpp
src/wayland/pxTimerNative.cpp
src/wayland_egl/pxTimerNative.cpp

milliseconds to be splitted in tv_sec and tv_usec(microsecond)
in struct timeval as 64bit linux kernel throws EINVAL error code
if value greater than 1sec (1000000L in terms of microsec) is
given to tv_usec whereas it works for any value in 32bit linux kernel.
glibc invokes kern_select()/select() kernel function in 32bit linux
kernel but it invokes do_pselect() kernel function for 64bit.
Ref. https://github.com/lattera/glibc/blob/master/sysdeps/unix/sysv/linux/select.c#L37
kern_select()/select() function splitted the value properly to
tv_sec and tv_usec fields in kernel level whereas do_pselect()
passes the value as same as copied from user space.
Ref. https://github.com/raspberrypi/linux/blob/rpi-4.19.y/fs/select.c#L673
To make uniformity on both 32bit and 64bit kernels, milliseconds …

pxSleepMS: handling timeval struct properly

---

examples/pxScene2d/src/pxVideo.cpp
examples/pxScene2d/src/pxVideo.h

This change fixes pxVideo playback being terminated by glib after EndOfStream event is handled.

pxVideo player loop and player thread created in constructor

---

examples/pxScene2d/src/pxVideo.cpp

As this cpp file uses std::bind function, this functional header is mandatory. This will resolve build issues.

pxVideo.cpp - Added functional cpp header
