examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/jsbindings/start.js

Cleaned out reference to xre framework from prototype.
Added base package reference when working with relative file references.
Set original package url.

Cleanup and set up of base package uri

---

examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/jsbindings/rcvrcore/SceneModuleLoader.js
examples/pxScene2d/src/jsbindings/rcvrcore/utils/FileArchive.js

First phase switch to native fileArchive

First phase switch to native fileArchive

---

examples/pxScene2d/src/Makefile_glut
examples/pxScene2d/src/jsbindings/binding.gyp
examples/pxScene2d/src/jsbindings/browser.js
examples/pxScene2d/src/jsbindings/start.sh
examples/pxScene2d/src/pxContext.h
examples/pxScene2d/src/pxContextGL.cpp
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h
src/glut/pxWindowNative.cpp
src/glut/pxWindowNative.h
src/pxWindowUtil.cpp

These are the initial changes commited to my fork of branch _temp_pxcore2_stage for westeros integration.

 temp pxcore2 stage - westeros integration

---

examples/pxScene2d/src/jsbindings/browser.js
examples/pxScene2d/src/jsbindings/load.js
examples/pxScene2d/src/jsbindings/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/pxConstants.cpp
examples/pxScene2d/src/pxConstants.h
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/rtObjectMacros.h

Api review

---

examples/pxScene2d/external/westeros-stub/westeros-compositor.h
examples/pxScene2d/external/westeros-stub/westeros-stub.cpp
examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h

Requires the hinting support update to westeros

Add support for fast path hinting to pxWayland.

---

examples/pxScene2d/src/rpc/tests/Makefile
examples/pxScene2d/src/rpc/tests/rtRpcTest.cpp
examples/pxScene2d/src/rpc/tests/rtTestCommon.h

Initial version of google test cases are added for RPC component

Initial version of google test cases are added for RPC Component

---

examples/pxScene2d/src/rpc/tests/testObject1.cpp
examples/pxScene2d/src/rpc/tests/testString1.cpp
examples/pxScene2d/src/rpc/tests/testValue1.cpp

Added google test cases to test rtObject, rtString and rtValues function boundaries

Added google test cases to test rtObject rtString and rtValues

---

examples/pxScene2d/src/Makefile
examples/pxScene2d/src/pxScene.cpp
examples/pxScene2d/src/rtUrlUtils.cpp
examples/pxScene2d/src/rtUrlUtils.h

Add url encoding

---

examples/pxScene2d/src/rpc/tests/rtRpcObjectCacheTest.cpp

Added google test cases for Objectcache class

Added google test cases for Objectcache

---

examples/pxScene2d/src/rpc/rtRemoteClient.cpp

This is the same change, we added in temp_refactor for property get.

Adding the change for property get to return status code, if it is not OK

---

examples/pxScene2d/src/Makefile
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h
examples/pxScene2d/src/rpc/Makefile
examples/pxScene2d/src/rpc/rtRemoteConfigGen.cpp
examples/pxScene2d/src/rpc/rtRemoteEnvironment.h
examples/pxScene2d/src/rpc/rtRemoteFunction.cpp
src/Makefile.x11_dfb

Some fixes and cherry-picks from _temp_refactor branch

Some fixes and cherry-picks from _temp_refactor branch

---

examples/pxScene2d/src/pxFileCache.cpp
examples/pxScene2d/src/pxFileCache.h
examples/pxScene2d/src/pxFileDownloader.cpp
examples/pxScene2d/src/pxFileDownloader.h
examples/pxScene2d/src/pxHttpCache.cpp
examples/pxScene2d/src/pxHttpCache.h
examples/pxScene2d/src/pxResource.cpp
tests/pxScene2d/test_imagecache.cpp

Changes for cleaning up build warnings introduced by the http file cache

---

examples/pxScene2d/src/pxArchive.cpp
examples/pxScene2d/src/pxArchive.h
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h

Changes for removing scene and its memory from javascript

---

examples/pxScene2d/src/pxArchive.cpp
examples/pxScene2d/src/pxArchive.h
examples/pxScene2d/src/pxFileDownloader.cpp
examples/pxScene2d/src/pxFileDownloader.h
examples/pxScene2d/src/pxHttpCache.cpp
examples/pxScene2d/src/pxHttpCache.h
examples/pxScene2d/src/pxResource.cpp
examples/pxScene2d/src/pxResource.h

Isolate cache functionality from main thread to improve performance

---

examples/pxScene2d/src/jsbindings/rtWrapperUtils.cpp

Changes for destroying javascript elements when no longer needed

---

examples/pxScene2d/external/libnode-v0.12.7/lib/dns.js

Change default family to Ipv4 addresses if undefined

---

examples/pxScene2d/src/Makefile

added static version of pxscene library

---

examples/pxScene2d/src/rtNode.cpp

changes for handle exceptions from libnode

---

examples/pxScene2d/src/Makefile

making rtthreadqueue dependent for libpxwayland

---

examples/pxScene2d/external/libnode-v0.12.7/configure
examples/pxScene2d/src/Makefile
src/x11/pxEventLoopNative.cpp

Please review and merge this change for building pxscene as static libs for Rng150

Changes for building pxscene as static libs for use by Rng150

---

examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h

Please review this change regarding WKIT-745

Call rtRemoteLocate on main thread

---

examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h
examples/pxScene2d/src/pxWaylandContainer.cpp

Making remote object locator thread configurable

---

src/rtNode.cpp

Problem seen is node engine gets destroyed before context, due to which crash is happening while accessing dangling pointers.

Fix crash in mac on abnormal termination

---

.travis.yml
build_linux.sh
build_osx.sh
testrunner_linux.sh
testrunner_osx.sh

- Test runner support
- Fix for errors during pull requests

Continous Integration support Phase 2

---

examples/pxScene2d/src/pxScene.cpp

export the environment variable BREAK_ON_SCRIPTSTART=1 to break on startup

Making javascript break on startup configurable by end-user.

---

remote/tests/Makefile
remote/tests/perf_client.cpp
remote/tests/perf_server.cpp

For testing:
Copy "librtCore.so" and "librtRemote.so" to tests directory.
cd tests/
make ;
commands :
export LD_LIBRARY_PATH=.
/perf_server -i "test"
./perf_client -i "test" -c 10

performace client functionality

---

.travis.yml
examples/pxScene2d/src/pxScene.cpp
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/rcvrcore/scene.1.js
examples/pxScene2d/src/shell.js
examples/pxScene2d/src/testRunner_memcheck.js
pxleakcheck_linux.sh
src/glut/pxWindowNative.cpp
src/rtNode.cpp

Automated validation of pxobject and texture memory usage in travis

Travis automation for px leaks and few fixes for memory leaks

---

examples/pxScene2d/src/pxScene2d.h
src/rtObject.cpp
tests/pxScene2d/Makefile
tests/pxScene2d/test_api.cpp

This is the do-over. Fresh FORK ... cleaner lineage

Added error checking of Args

---

examples/pxScene2d/src/browser.js
examples/pxScene2d/src/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/rcvrcore/Logger.js
examples/pxScene2d/src/rcvrcore/SceneModuleLoader.js
examples/pxScene2d/src/rcvrcore/SceneModuleManifest.js
examples/pxScene2d/src/rcvrcore/XModule.js
examples/pxScene2d/src/rcvrcore/pxRoot.js
examples/pxScene2d/src/rcvrcore/rpcContext.js
examples/pxScene2d/src/rcvrcore/rpcController.js
examples/pxScene2d/src/rcvrcore/scene.1.js
examples/pxScene2d/src/rcvrcore/tools/keys.js
examples/pxScene2d/src/rcvrcore/utils/FileArchive.js
examples/pxScene2d/src/shell.js

VSCode | JSHint - reduced warnings ... simple ones.

VSCode | JSHint - reduced warnings

---

examples/pxScene2d/src/rcvrcore/AppSceneContext.js

This problem is seen after introduction of new cleartimeout function.

fix leaks due to module exports

---

examples/pxScene2d/src/browser/editbox.js
examples/pxScene2d/src/rcvrcore/tools/keys.js

Edit box now handles LONG content... with appropriate scrolling of view - clipped by bounds.

EditBox now handles long content with a clip rect / scroll view design

---

examples/pxScene2d/src/browser/editbox.js

Fix for clicked Focus within Edit Box .. passing through the Focus

Fix for clicked Focus within Edit Box

---

examples/pxScene2d/src/pxContextGL.cpp

Adding GL_GLEXT_PROTOTYPES macro for refsw-16.2's gle2ext.h.

---

examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/rcvrcore/AppSceneContext.js
src/jsbindings/rtWrapperUtils.cpp

fix for pxobject leaks without parent and crash from removeAll

---

examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/rcvrcore/AppSceneContext.js
src/jsbindings/rtWrapperUtils.cpp

Reverts johnrobinsn/pxCore#405

Revert "fix for pxobject leaks without parent and crash from removeAll"

---

ci/build_px.sh
ci/pxleakcheck_linux.sh
ci/pxleakcheck_osx.sh
ci/script.sh
ci/testrunner_linux.sh
ci/testrunner_osx.sh
ci/unittests_linux.sh
examples/pxScene2d/src/testRunner_memcheck.js
tests/pxScene2d/testRunner/tests.json
tests/pxScene2d/test_pxUtil.cpp

Let's discuss if we want to merge this in short term, then move forward with addressing memory leaks.

Test runner

---

src/rtObjectMacros.h

Fixed a nasty typo in *rtObjectMacros.h* ... and case corrected some other tokens to match surroundings

Typos fixed

---

examples/pxScene2d/src/pxWaylandContainer.cpp
examples/pxScene2d/src/pxWaylandContainer.h

Signed-off-by: Jeff Wannamaker <jeff_wannamaker@cable.comcast.com>

Fix leak of pxWayland objects on dispose

---

examples/pxScene2d/src/pxWayland.cpp
src/pxKeycodes.h

Signed-off-by: nrajang <nambirajan.g@lnttechservices.com>

Linux Key code for Color keys are correctly mapped

---

examples/pxScene2d/src/browser.js
examples/pxScene2d/src/browser/editbox.js

Better Double-Click to Highlight ALL

---

examples/pxScene2d/src/pxWayland.cpp

Signed-off-by: aansari <AzamAyub_Ansari@cable.comcast.com>

Proper linux keycodes are assigned to colore keys.

---

examples/pxScene2d/README.md

Use pxCore/src to skip build of all examples other than pxScene2d.

Change directory for glut make

---

examples/pxScene2d/src/pxAnimate.cpp
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
tests/pxScene2d/testRunner/tests.json

Revert "resolve promise rather than rejecting for canceled animations"

---

src/rtNode.cpp
src/rtNode.h
tests/pxScene2d/supportfiles/simple.js
tests/pxScene2d/test_rtnode.cpp

Additions to improve Code Coverage / Unit Tests
Local testing suggests that it's 80.5% for rtNode.cpp

Additions to improve Code Coverage / Unit Tests

---

examples/pxScene2d/external/build.sh

Scale build process by examining the number of cores available.  
Windows is stuck with 3 parallel builds until someone provides logic 
for that.
Swap openssl for GnuTLS in libcurl when openssl is too new for the
version of libcurl that we're stuck with.

Scale make parallelism with cores, curl/ssl fix

---

examples/pxScene2d/src/browser.js
examples/pxScene2d/src/browser/editbox.js

Fixes for CTRL-L and some focus wonky stuff

Fixes for CTRL-L and some focus wonky stuff

---

src/rtFileDownloader.cpp
src/rtFileDownloader.h

Added data download progress callback, so user can get the callback while download in progress.

  Added Data download progress callback.

---

ci/generate_cache.py

Add org to script to allow use on pxscene organization as well as on branches.

Add org to script

---

ci/deploy_pxscene.py
ci/pxscene_deploy_rules.json

Add org and branch to release script so that org can be passed in as either fork owner or pxscene org name; add branch so that we can build off specific tag; add message so that release build has an obvious name in Travis.

change script to take branch and org parameters

---

examples/pxScene2d/src/pxContextGL.cpp
examples/pxScene2d/src/rasterizer/pxCanvas.cpp
examples/pxScene2d/src/rasterizer/pxCanvas2d.cpp
examples/pxScene2d/src/rasterizer/pxCanvas2d.h
examples/pxScene2d/src/rasterizer/pxPath.cpp
examples/pxScene2d/src/rasterizer/pxPath.h
examples/pxScene2d/src/rasterizer/svgtest.js
examples/pxScene2d/src/rasterizer/test.svg
examples/pxScene2d/src/rcvrcore/scene.1.js
src/mac/pxWindowNative.mm

Adding support for SVG Rounded Rectangles ... some other optimizations

SVG Rounded Rectangles

---

.travis.yml
ci/after_script.sh
ci/pxscene_generate_cache.json

This reverts commit fce99ab55a520a91876e76659db8fcc530d5d6b6.

Revert "Change address for ci results server"

---

examples/pxScene2d/src/pxScene2d.cpp

Fix repaint bug for moveToFront and moveToBack.

Trigger repaints and mark scene as dirty for moveToFront and moveToBack

---

remote/rtRemoteAsyncHandle.cpp
remote/rtRemoteAsyncHandle.h
remote/rtRemoteClient.cpp
remote/rtRemoteClient.h

This handles the case when remote peer closed connection/crashed while
handling the request.

Check connection state while waiting for response.

---

examples/pxScene2d/external/westeros-stub/westeros-compositor.h
examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h

Signed-off-by: nrajang <nambirajan.g@lnttechservices.com>

Resoving decoderHandle datatype mismatch

---

.github/CONTRIBUTING.md
.github/TESTRUNNER.md
README.md

- Add CONTRIBUTING
- Add TESTRUNNER
- Edit main README

Add info on contributing and testRunner

---

examples/pxScene2d/src/pxTextBox.cpp
examples/pxScene2d/src/pxTextBox.h

Remove unused function as part of adding CI tests for textBox.

remove unused function

---

ci/before_install.sh
ci/before_script.sh
ci/build_linux.sh
ci/build_osx.sh
ci/build_px.sh
ci/check_dump_cores_linux.sh
ci/check_dump_cores_osx.sh
ci/code_coverage.sh
ci/code_coverage_linux.sh
ci/code_coverage_osx.sh
ci/execute_linux.sh
ci/execute_osx.sh
ci/monitor.sh
ci/unittests_linux.sh
ci/unittests_osx.sh

Indentation for ci scripts are done for improving readability

Scripts Indentation

---

ci/before_install.sh
examples/pxScene2d/README.md

Add quilt install requirement for OSX. Do we need similar for Windows?

Add quilt for osx

---

examples/pxScene2d/external/westeros-stub/westeros-compositor.h
examples/pxScene2d/src/pxWayland.cpp
examples/pxScene2d/src/pxWayland.h

Since Helio player is abandoned. We are reverting related changes.
Signed-off-by: nrajang <nambirajan.g@lnttechservices.com>

Reverting DecodeHandler passing code.

---

ci/release_osx.sh

To trigger corn job, the settings needs to be updated  in travis account.
In Travis Page : More Options->Settings->Cron Jobs. Master branch has to be selected and the cron job trigger frequency (Interval) can be set as required.

Upload the osx binary to build server

---

appveyor.yml
ci/after_build_win32.bat
ci/build_win32.bat

Steps to be done before merging this PR on master branch.
By default cron job feature is disable in free accounts. Please request in this link for getting it enabled for master branch.
https://help.appveyor.com/
For Encrypting the key file and using the secure key in appveyor.yml for pxcore account.
1. In windows command prompt, Install secure-file package "nuget install secure-file -ExcludeVersion".
2. Change directory to the installed secure-file package <user-dir>\secure-file\tools.
3. Execute the command to encrypt the pxscene-build.pem.ppk file. "secure-file.exe -encrypt "pxscene-build.pem.ppk" -secret <secure_key>".
4. Login to Appveyor pxCore Account and goto User Profile (Profile Name) -> Tools -> Encrypt data. Provide the <secure_key> used in third step and click on Encrypt …

Cron job support for Windows

---

examples/pxScene2d/src/pxContextGL.cpp

* previous fix was over simplified and did not work for real image borders

Fix drawing of border in drawImage9Border2 again

---

examples/pxScene2d/README.md

Revert "Updated README.md for the new compiler flag"

---

ci/execute_osx.sh
examples/pxScene2d/src/rcvrcore/utils/AccessControl.js
tests/pxScene2d/testRunner/tests.json

+ Prefer host over hostname for CORS/permissions check in http modules to support IPv6 URLs

Add test_permissionsDefault.js in CI tests

---

tests/pxScene2d/test_imagecache.cpp

This fixes the following crash:
Thread 3 "pxscene2dtests" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f0703aff700 (LWP 6252)]
0x00007f070eea114c in __tsan_func_entry () from /lib64/libtsan.so.0
(gdb) bt
#0  0x00007f070eea114c in __tsan_func_entry () from /lib64/libtsan.so.0
#1  0x00000000005af843 in realloc (ptr=0x0, size=32) at pxCore/tests/pxScene2d/test_imagecache.cpp:43
#2  0x00007f070a988645 in pthread_getattr_np (thread_id=<optimized out>, attr=<optimized out>) at pthread_getattr_np.c:176
#3  0x00007f070eeba185 in __sanitizer::GetThreadStackTopAndBottom(bool, unsigned long*, unsigned long*) () from /lib64/libtsan.so.0
#4  0x00007f070eeba617 in __sanitizer::GetThreadStackAndTls(bool, unsigned long*, unsigned long*, unsigned long*, unsigned long*) () from …

fix SIGSEGV caused by redefining realloc()

---

examples/pxScene2d/src/shell.js

Revert "Temp clearscreen delegate refactor"

---

examples/pxScene2d/src/pxFont.cpp
examples/pxScene2d/src/pxFont.h
examples/pxScene2d/src/pxResource.cpp
examples/pxScene2d/src/pxResource.h
examples/pxScene2d/src/pxScene.cpp
src/rtFileDownloader.cpp
src/rtFileDownloader.h
src/unix/rtThreadPoolNative.h
src/win/rtThreadPoolNative.h

Reverting thread contention cleanup for short term

---

.github/CONTRIBUTING.md
.github/TESTRUNNER.md

TESTRUNNER.md and CONTRIBUTING.md are updated with the latest testRunner and tests file path.

Updated the documents with latest testRunner path

---

examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
tests/pxScene2d/testRunner/tests.json

Incorporated comments from Mike to cleanup code inside pxScene2d::bubbleEventOnBlur.

Added loseFocusChain bool property for onBlur Event

---

remote/rtRemoteAdaptor/rtRemoteAdapter.cpp
remote/rtRemoteAdaptor/rtRemoteAdapter.h
remote/rtRemoteAdaptor/rtSampleServer.cpp

1.Replacing printf with rtLog.
2.Using new & delete in place of malloc & free.
3.Removing unnecessary sprintf.
4.Adding "return" to methods.
5.Few other small changes.

Modifying few things:

---

examples/pxScene2d/src/rcvrcore/scene.1.js
examples/pxScene2d/src/shell.js
src/mac/pxEventLoopNative.mm

Revert "Web style color syntax ..."

---

examples/pxScene2d/src/pxTextBox.cpp

The original fix was broken by a subsequent commit.

fix issue with thin characters

---

remote/rtRemoteClient.cpp
remote/rtRemoteServer.cpp
remote/rtRemoteValueReader.cpp

Add log messages when RT_ERROR_PROTOCOL_ERROR is being returned.
These messages will show the function and actual reason of such error code.

Log error RT_ERROR_PROTOCOL_ERROR

---

remote/rtRemoteEnvironment.cpp

Return RT_FAIL if m_running is false. Log errors in these cases.

Fail and log errors if env is not running

---

remote/Makefile
remote/js/examples/rtservicemanager.js
remote/js/lib/RTRemoteMulticastResolver.js
remote/js/lib/RTRemoteProtocol.js
remote/rtRemoteServer.cpp

1.Adding protocol injection case(RTRemoteProtocol.js) for method call response
2.Allowing to listen to interface other than loopback(remote/Makefile, remote/rtRemoteServer.cpp)
3.Adding rtservicemanager.js file to test communication with service manager.

 Access of service manager from another device.

---

remote/Makefile
remote/js/examples/rtServiceManager.js
remote/js/examples/rtservicemanager.js
remote/js/examples/testProxy.js
remote/js/lib/RTRemoteMulticastResolver.js
remote/js/lib/RTRemoteProtocol.js
remote/js/lib/RTRemoteProxy.js
remote/rtRemoteAdaptor/rtRemoteAdapter.cpp
remote/rtRemoteAdaptor/rtRemoteAdapter.h
remote/rtRemoteServer.cpp

clean up the code(rt remote adapter)

Code clean up 

---

examples/pxScene2d/VSCODE_DEBUG.md

Updated Markdown instructions to include fix for VS Code 1.25+

Updated to include FIX & NOTE on 1.25

---

examples/pxScene2d/external/nanosvg/patches/add_CoverityWarningFix.diff

* Adding Coverity fixes
* Updates to Coverity warning patch
* Fixed patch order for 'nanosvg'

Updates to Coverity warning patch (#1319)

---

examples/pxScene2d/src/pxFont.cpp

Revert "Changes for font cutoffs in higher freetype versions"

---

tests/pxScene2d/testRunner/tests.json

Adding testing for OSCILLATE animation property

---

ci/execute_linux.sh
ci/execute_osx.sh
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxScene2d.h
examples/pxScene2d/src/rcvrcore/AppSceneContext.js
examples/pxScene2d/src/rcvrcore/utils/FileUtils.js
tests/pxScene2d/testRunner/tests.json
tests/pxScene2d/test_jsfiles.cpp
tests/pxScene2d/test_rtSettings.cpp

This reverts commit 521122d436abac9f75aceb6a3c915baa044fc681.

reverting PR 1249

---

remote/rpc_main.cpp
remote/rtRemote.cpp
remote/rtRemote.h
remote/rtSampleClient.cpp
remote/rtSampleServer.cpp
remote/tests/Makefile
remote/tests/perf_client.cpp
remote/tests/perf_driver.cpp
remote/tests/perf_server.cpp

This fixes 'XRE2-1539.  It should have low impact, only affecting remote test apps.

Xre2 1539v2

---

src/win/pxWindowNative.cpp
src/win/pxWindowNative.h

Verified with mouse scroll option and it looks working fine.
Whereas with the windows touchpad option, the scrolling is not as fine as the mouse scroll.

Mouse wheel support for windows 

---

examples/pxScene2d/src/v8_modules/console.js
examples/pxScene2d/src/v8_modules/querystring.js
src/rtHttpRequest.cpp
src/rtHttpRequest.h
src/rtHttpResponse.cpp
src/rtHttpResponse.h

- normal string formatting for console module
- a crash when parsing empty headers
- extra methods (once, removeAllListeners) for http classes

fixes for v8:

---

ci/leak.supp
examples/pxScene2d/src/rcvrcore/AppSceneContext.js
src/rtScriptV8/rtScriptNode.cpp
src/rtScriptV8/rtWrapperUtils.cpp
src/rtScriptV8/rtWrapperUtils.h

* leak.supp had too specific items (3xx-byte leaks)
* fix a leak in asyncFileAcquisition (40-byte leaks)
* print objects on exit

fix random leaks

---

examples/pxScene2d/src/rcvrcore/AppSceneContext.js

keep the following API:
- module.appSceneContext.packageUrl
- module.appSceneContext.getPackageBaseFilePath
- module.appSceneContext.getFile
- module.exports

wrap xModule exposed as 'module'

---

examples/pxScene2d/src/rcvrcore/optimus.js

Provided new logging info about uri of failed spark application.

XRE-13676 : Optimus application couldn't launch due to error

---

examples/pxScene2d/src/browser.js
examples/pxScene2d/src/browser/editbox.js

Changed "rect" to "object" on `container` in **editbox.js**

Fix Black Frame on Input box + ws removal

---

examples/pxScene2d/src/pxObject.cpp
examples/pxScene2d/src/pxObject.h
examples/pxScene2d/src/pxScene2d.cpp
tests/pxScene2d/testRunner/tests.json

Updated PR ... I'll close 1693

Accept "200ms" type strings for animations

---

examples/pxScene2d/external/libnode-v6.9.0/configure

Added support for aarch64 keeping arm64 also for compatibility.

libnode: added aarch64 support

---

examples/pxScene2d/pxScene2d_xcode/spark.sh
examples/pxScene2d/src/macstuff/spark.sh
examples/pxScene2d/src/mkdeploy.sh

Spark repo changes are merged in and this change is good to get merged

changing auto-update url from pxscene.org to sparkui.org

---

examples/pxScene2d/src/browser/editbox.js

Small update in editbox to support new app

XRE2-2078 : Create FlingTo test app

---

examples/pxScene2d/external/libnode-v6.9.0/deps/v8/src/objects-body-descriptors.h

tested with gcc 7.4.0, ubuntu 18.04

ubuntu 18 support with node 6

---

src/rtFileDownloader.cpp
src/rtFileDownloader.h
tests/pxScene2d/test_imagecache.cpp

The user configurable curl options such as set userAgent, enable/disable CROSRequired, manualRedirectionHandling, enable download metrics, set connection timeout, etc.,
Improved byte-rage logic.

Added user configurable curl options

---

src/rtFileCache.cpp
src/rtFileDownloader.cpp
src/rtFileDownloader.h
src/rtHttpCache.cpp
src/rtString.cpp
src/rtString.h
tests/pxScene2d/test_imagecache.cpp

Added support for byte range curl download

Added support for byte range curl download

---

examples/pxScene2d/src/pxFont.cpp
examples/pxScene2d/src/pxFont.h
examples/pxScene2d/src/pxScene2d.cpp
examples/pxScene2d/src/pxText.cpp
examples/pxScene2d/src/pxTextCanvas.cpp
examples/pxScene2d/src/pxTextCanvas.h

Revert "pxTextCanvas: support for CutSx, CutSy, CutEx, CutEy, fontStyle in Lightning++"

---

examples/pxScene2d/src/initGL.js
examples/pxScene2d/src/node_modules/sparkHttp_wrap.js

* replace node-fetch with sparkHttp
* fix sparkHttp_wrap
* fix url parse

replace node-fetch with sparkHttp (#2063)

---

examples/pxScene2d/src/pxVideo.cpp

Removed gst_deinit from pxVideo.

removed gst_deinit from pxVideo

---

examples/pxScene2d/src/pxVideo.cpp
examples/pxScene2d/src/pxVideo.h

Implemented methods:
pxVideo::availableAudioLanguages
pxVideo::availableSpeeds
pxVideo::duration
pxVideo::setZoom
pxVideo::volume
pxVideo::setVolume
pxVideo::position
pxVideo::setPosition
pxVideo::audioLanguage
pxVideo::setAudioLanguage
pxVideo::setPositionRelative

pxVideo - implement part of missing functionalities

---

examples/pxScene2d/src/pxVideo.cpp
examples/pxScene2d/src/pxVideo.h

Please merge first PR "pxVideo fixed crash when autoPlay set to false" and then this PR.

pxVideo support for EndOfStream and ProgrssUpdate events

---

examples/pxScene2d/pxScene2d_xcode/makeLocalLibs.sh

Fix persmission for Xcode build.

---

cmake/DukeDeps.cmake

Windows: uvlib issue fixed

---

examples/pxScene2d/src/rcvrcore/AppSceneContext.js

The Spark Apps should be able to use ThunderJS to communicate with Thunder plugins.

Added Support for ThunderJS

---

examples/pxScene2d/src/jsc_modules/fs.js
examples/pxScene2d/src/jsc_modules/module.js
examples/pxScene2d/src/jsc_modules/process.js
examples/pxScene2d/src/jsc_modules/timers.js
examples/pxScene2d/src/jsc_modules/util.js
examples/pxScene2d/src/rcvrcore/ESMLoader.js
examples/pxScene2d/src/rcvrcore/initGL.js
src/rtScriptJSC/rtJSCBindings.cpp
src/rtScriptJSC/rtJSCWrappers.cpp
tests/pxScene2d/test_pxTimerNative.cpp

triangle2.js works with this PR

fix jsc suport for lightning
